name: Pipeline

on:
  push:
    branches: [ "mainline" ]
  pull_request:
    branches: [ "mainline" ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
       - name: Getting Project
         uses: actions/checkout@v4.0.0
          
       - name: Setup Java JDK
         uses: actions/setup-java@v3.12.0
         with:
          java-version: '17'
          distribution: 'temurin'

       - name: Run Gradle Build
         run: gradle build

       - name: Create DIR for Artifacts
         run: mkdir Artifacts &&
              mv Dockerfile Artifacts &&
              mv build/libs/GameZone-0.0.1-SNAPSHOT.jar Artifacts
         
       - name: Upload The Artifacts
         uses: actions/upload-artifact@v3.1.3
         with:
           name: Build-${{ github.sha }}
           path: Artifacts

  Alpha:
    needs: Build 
    runs-on: ubuntu-latest
    steps:
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
          
      - name: Login To Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      - name: Setup Java JDK
        uses: actions/setup-java@v3.12.0
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Download The Build Artifacts
        uses: actions/download-artifact@v2.1.1
        with:
          name: Build-${{ github.sha }}

      - name: Print
        run: ls

      - name: Deploying The Application
        run: (java -jar GameZone-0.0.1-SNAPSHOT.jar) 
             & (sleep 60 ;
                  echo PostMan Tests Started ;
                  postman collection run "28989418-3a3c5990-6a0a-41d6-a601-6cfad04ac644" --integration-id "148257-${{ github.run_id }}" ; 
                  echo Tests Completed ; exit $?)
         
  Packaging:
    needs: Alpha
    runs-on: ubuntu-latest
    steps:
        - name: Download The Build Artifacts
          uses: actions/download-artifact@v2.1.1
          with:
           name: Build-${{ github.sha }}
        
        - name: Moving Jar
          run: mkdir build &&
               mkdir build/libs &&
               mv GameZone-0.0.1-SNAPSHOT.jar build/libs
        
        - name: Setup Docker
          uses: docker/setup-qemu-action@v2.2.0
          
        - name: Create Docker Image
          run: docker build -t gamezone-${{ github.sha }}:gamezone .

        - name: Upload Docker Image
          uses: ishworkh/container-image-artifact-upload@v1.0.0
          with:
            image: gamezone-${{ github.sha }}:gamezone

  Beta:
    needs: Packaging
    runs-on: ubuntu-latest
    steps:
        - name: Install Postman CLI
          run: |
                curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
          
        - name: Login To Postman CLI
          run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
          
        - name: Setup Docker
          uses: docker/setup-qemu-action@v2.2.0
          
        - name: Download Docker Image
          uses: ishworkh/docker-image-artifact-download@v2.1.0
          with:
            image: gamezone-${{ github.sha }}:gamezone

        - name: Deploying The Application
          run: (docker run -p 8080:8080 gamezone-${{ github.sha }}:gamezone) 
             & (sleep 60 ;
                  echo PostMan Tests Started ;
                  postman collection run "28989418-3a3c5990-6a0a-41d6-a601-6cfad04ac644" --integration-id "148257-${{ github.run_id }}" ; 
                  echo Tests Completed ; exit $?)
          
