name: Packaging

on:
  push:
    branches: [ "mainline" ]
  pull_request:
    branches: [ "mainline" ]
  workflow_dispatch:

jobs:
  Packaging:
    runs-on: ubuntu-latest
    steps:
        - name: Setup Docker
          uses: docker/setup-qemu-action@v2.2.0
    
    
    
