name: Pipeline

on:
  push:
    branches: [ "mainline" ]
  pull_request:
    branches: [ "mainline" ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
       - name: Getting Project
         uses: actions/checkout@v4.0.0
          
       - name: Setup Java JDK
         uses: actions/setup-java@v3.12.0
         with:
          java-version: '17'
          distribution: 'temurin'
         
       - name: Run Gradle Build
         run: gradlew build
         
  Packaging:
    needs: Build 
    runs-on: ubuntu-latest
    steps:
        - name: Getting Project
          uses: actions/checkout@v4.0.0
    
        - name: Setup Docker
          uses: docker/setup-qemu-action@v2.2.0
          
        - name: Create an Image
          working-directory: '.'
          run: docker build -t gamezone:gamezone .

        - name: Save Image
          uses: ishworkh/container-image-artifact-upload@v1.0.0
          with:
            image: "gamezone:gamezone"
            retention_days: "2"
