name: Pipeline

on:
  push:
    branches: [ "mainline" ]
  pull_request:
    branches: [ "mainline" ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
       - name: Setup Java JDK
         uses: actions/setup-java@v3.12.0
         with:
          java-version: '17'
          distribution: 'temurin'

       - name: Initializing Gradle
         run: gradle init
         
       - name: Run Gradle Build
         run: gradle build
         
  Packaging:
    needs: Build 
    runs-on: ubuntu-latest
    steps:
        - name: Setup Docker
          uses: docker/setup-qemu-action@v2.2.0

        - name: Create an Image
          run: docker build -t gamezone:gamezone .
          working-directory: '.'
    
    
    
