name: ScalingoPipeline

on:
  push:
    branches: [ "mainline" ]
  pull_request:
    branches: [ "mainline" ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
       - name: Getting Project
         uses: actions/checkout@v4.0.0
          
       - name: Setup Java JDK
         uses: actions/setup-java@v3.12.0
         with:
          java-version: '17'
          distribution: 'temurin'

       - name: Run Gradle Build
         run: gradle build
         
  Beta:
    needs: Build 
    runs-on: ubuntu-latest
    steps:
      - name: Getting Project
        uses: actions/checkout@v4.0.0

      - name: Setup Java JDK
        uses: actions/setup-java@v3.12.0
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create Jar
        run: gradle bootJar

      - uses: actions/checkout@v3
      
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
          
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      - name: Create Test Script
        working-directory: "./build/libs"
        run: echo -e "sleep 60 \n 
             postman collection run "28989418-3a3c5990-6a0a-41d6-a601-6cfad04ac644" --integration-id "148257-${{ github.run_id }}" \n
             postman api lint 440cb951-f437-470a-8085-3e0e90a57263 --integration-id 148257 \n
             echo Tests are done \n
             exit" | tee testScript.sh

      - name: Running The Application
        working-directory: "./build/libs"
        run: java -jar GameZone-0.0.1-SNAPSHOT.jar 
             & sh testScript.sh
