name: ScalingoPipeline

on:
  push:
    branches: [ "mainline" ]
  pull_request:
    branches: [ "mainline" ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
       - name: Getting Project
         uses: actions/checkout@v4.0.0
          
       - name: Setup Java JDK
         uses: actions/setup-java@v3.12.0
         with:
          java-version: '17'
          distribution: 'temurin'

       - name: Run Gradle Build
         run: gradle build
         
  Beta:
    needs: Build 
    runs-on: ubuntu-latest
    steps:
      - name: Getting Project
        uses: actions/checkout@v4.0.0

      - name: Setup Java JDK
        uses: actions/setup-java@v3.12.0
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create Jar
        run: gradle bootJar

      - name: Running The Application
        working-directory: "./build/libs"
        run: java -jar GameZone-0.0.1-SNAPSHOT.jar
