name: ScalingoPipeline

on:
  push:
    branches: [ "mainline" ]
  pull_request:
    branches: [ "mainline" ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
       - name: Getting Project
         uses: actions/checkout@v4.0.0
          
       - name: Setup Java JDK
         uses: actions/setup-java@v3.12.0
         with:
          java-version: '17'
          distribution: 'temurin'

       - name: Run Gradle Build
         run: gradle build
         
  Beta:
    needs: Build 
    runs-on: ubuntu-latest
    steps:
      - name: Getting Project
        uses: actions/checkout@v4.0.0

      - name: Setup Java JDK
        uses: actions/setup-java@v3.12.0
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create Jar
        run: gradle bootJar

      - uses: actions/checkout@v3
      
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
          
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      - name: Running The Application
        run: java -jar ./build/libs/GameZone-0.0.1-SNAPSHOT.jar 
             & sh ./scripts/postmantest.sh
